version: "3.9"
services:

  postgres:
    image: registry.gitlab.com/dalibo/postgresql_anonymizer:stable
    environment:
      POSTGRES_DB: "itmo"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "6432:5432"